# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More on GitHub Actions for Azure: https://github.com/Azure/actions

name: AWS Deploy - Build and deploy Node.js app - csc307-backend

on:
  push:
    branches:
      - ci-cd-aws
  workflow_dispatch: {}

# defaults:
#   run:
#     working-directory: expressjs-backend

# env:
#   AZURE_WEBAPP_PACKAGE_PATH: expressjs-backend # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node-version: [18.x]
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }} # ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present  
          npm run coverage --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        #See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }} # ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: csc307-backend
          environment_name: CSC307-backend-env
          version_label: 1.0.3
          region: us-west-2
          deployment_package: release.zip
