# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# optimize https://techcommunity.microsoft.com/t5/apps-on-azure-blog/how-to-reduce-the-deployment-time-using-the-file-compression/ba-p/3708095

name: Build and deploy Node.js app to Azure Web App - csc307-api-win

on:
  push:
    branches:
      - ci-cd-windows
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        env:
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
          MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER}}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # - name: Zip artifact for development job
      #   run: Compress-Archive -Path * -DestinationPath release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # - name: list files
      #   run: ls -lR

      # - name: unzip artifact for deployment
      #   run: Expand-Archive -Path release.zip -DestinationPath .
      #   working-directory: .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "csc307-api-win"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_35EB76A956764899B0C9F8ED8DC1C01E }}
